target-version = "py310"

select = [
    "A",       # flake8-builtins
    "ARG",     # flake8-unused-arguments
    "B",       # flake8-bugbear
    "BLE",     # flake8-blind-except
    "C",       # complexity
    "C4",      # flake8-comprehensions
    "C90",     # mccabe
    "D",       # docstrings
    "DTZ",     # flake8-datetimez
    "E",       # pycodestyle
    "EXE",     # flake8-executable
    "F",       # pyflakes/autoflake
    "FBT",     # flake8-boolean-trap
    "G",       # flake8-logging-format
    "I",       # isort
    "ICN",     # flake8-import-conventions
    "INP",     # flake8-no-pep420
    "ISC",     # flake8-implicit-str-concat
    "PGH004",  # Use specific rule codes when using noqa
    "PIE",     # flake8-pie
    "PLC0414", # Useless import alias. Import alias does not rename original package.
    "PYI",     # flake8-pyi
    "Q",       # flake8-quotes
    "RET",     # flake8-return
    "RSE",     # flake8-raise
    "S",       # flake8-bandit
    "SIM",     # flake8-simplify
    "SLF",     # flake8-self
    "T10",     # flake8-debugger
    "T20",     # flake8-print
    "TID",     # flake8-tidy-imports
    "TRY004",  # Prefer TypeError exception for invalid type
    "UP",      # pyupgrade
    "W",       # pycodestyle
    "YTT",     # flake8-2020
]

ignore = [
    "D203",  # 1 blank line required before class docstring
    "D213",  # Multi-line docstring summary should start at the second line
    "D404",  # First word of the docstring should not be This
    "D406",  # Section name should end with a newline
    "D407",  # Section name underlining
    "D411",  # Missing blank line before section
    "E731",  # Do not assign a lambda expression, use a def
]

[per-file-ignores]
"tests/*" = ["S101"]

[pyupgrade]
keep-runtime-typing = true

[mccabe]
max-complexity = 25
